<?php

/**
 * Implementation of hook_captcha_default_points_alter().
 *
 * Enable CAPTCHA integration for all Webforms.
 */
function divine_custom_hook_webform_component_presave(&$component) {
  // Only proceed if the Webform module is enabled.
  if (module_exists('webform')) {
    // Get the list of supported Webform content types.
    $webform_types = webform_node_types();
    if (!empty($webform_types)) {
      // Get a list of all nid's for all supported webform content types.
      $webforms = array();
      $nodes = db_select('node')
        ->fields('node', array('nid'))
        ->condition('type', $webform_types)
        ->execute(); 
      foreach ($nodes as $node) {
        // Webform form IDs follow this format.
        $webforms[] = 'webform_client_form_' . $node->nid;
      }

      // Enable CAPTCHA integration for each form, if it isn't already enabled.
      foreach ($webforms as $form_id) {
        if (!isset($items[$form_id])) {
          $captcha = new stdClass;
          $captcha->disabled = FALSE;
          $captcha->api_version = 1;
          $captcha->form_id = $form_id;
          $captcha->module = '';
          // This may be 'node', 'default', 'captcha/Math',
          // 'recaptcha/reCAPTCHA', etc.
          $captcha->captcha_type = 'recaptcha/reCAPTCHA';
          $items[$form_id] = $captcha;
        }
      }
    }
  }
}